export const CUSTOMER_ID = "MEAJOH,MEAJOH03";

export const MONTH_ABBR = ["JAN","FEB","MAR","APR","MAY","JUN","JUL","AUG","SEP","OCT","NOV","DEC"];

export const MODE_TABS = [
  { key: "SEA_AIR",       label: "Sea & Air" },
  { key: "CROSS_BORDER",  label: "Cross-border" },
  { key: "OCEAN_FREIGHT", label: "Ocean Freight" },
];

export const TEMPLATE_ITEMS = {
  SEA_AIR: [
    { type: "section",  label: "On-time Shipment Clearing" },
    { type: "category", criterionId:  1, label: "On-time Customs clearance",                  kpiDays: "3",          targetKpi: "98%" },
    { type: "sub",      criterionId:  2, label: "- Sea Import - FCL (Container)" },
    { type: "sub",      criterionId:  3, label: "- Sea Import - FCL (Container) - Actual" },
    { type: "sub",      criterionId:  4, label: "- Sea Import - LCL (Shipment)" },
    { type: "sub",      criterionId:  5, label: "- Sea Import - LCL (Shipment) - Actual" },
    { type: "sub",      criterionId:  6, label: "- Air Import (Shipment)" },
    { type: "sub",      criterionId:  7, label: "- Air Import (Shipment) - Actual" },
    { type: "category", criterionId:  8, label: "On time arrival at W/H vs slot time",        kpiDays: "0.5 Hrs.",   targetKpi: "98%" },
    { type: "sub",      criterionId:  9, label: "- Sea Export (Container)" },
    { type: "sub",      criterionId: 10, label: "- Sea Export (Container) - Actual" },
    { type: "sub",      criterionId: 11, label: "- Sea Import (Container)" },
    { type: "sub",      criterionId: 12, label: "- Sea Import (Container) - Actual" },
    { type: "category", criterionId: 13, label: "On-time Billing",                            kpiDays: "14",         targetKpi: "98%" },
    { type: "sub",      criterionId: 14, label: "- Sea Import (Shipment)" },
    { type: "sub",      criterionId: 15, label: "- Sea Export (Shipment)" },
    { type: "sub",      criterionId: 16, label: "- Air Import (Shipment)" },
    { type: "sub",      criterionId: 17, label: "- Air Export (Shipment)" },
    { type: "category", criterionId: 18, label: "Return entry under BIS19/Status 04 on time", kpiDays: "10",         targetKpi: "98%" },
    { type: "sub",      criterionId: 19, label: "- Sea Export (Entry)" },
    { type: "sub",      criterionId: 20, label: "- Air Export (Entry)" },
    { type: "category", criterionId: 21, label: "Refund Import duty on time",                 kpiDays: "60",         targetKpi: "100%" },
    { type: "sub",      criterionId: 22, label: "- Re-Export Sea Import (Form D and COO)" },
    { type: "category", criterionId: 23, label: "Communication and Solution response",        kpiDays: "",           targetKpi: "98%" },
    { type: "sub",      criterionId: 24, label: "- Contact person responds (Urgently case)",  kpiDays: "24 Hrs." },
    { type: "sub",      criterionId: 25, label: "- Contact person responds (Normally case)",  kpiDays: "48 Hrs." },
    { type: "section",  label: "Accuracy" },
    { type: "category", criterionId: 26, label: "Billing Accuracy",                           kpiDays: "Hit/Missed", targetKpi: "100%" },
    { type: "sub",      criterionId: 27, label: "- Sea Import (Shipment)" },
    { type: "sub",      criterionId: 28, label: "- Sea Export (Shipment)" },
    { type: "sub",      criterionId: 29, label: "- Air Import (Shipment)" },
    { type: "sub",      criterionId: 30, label: "- Air Export (Shipment)" },
    { type: "category", criterionId: 31, label: "Draft customs entry accuracy",               kpiDays: "Hit/Missed", targetKpi: "100%" },
    { type: "sub",      criterionId: 32, label: "- Sea Import (Entry)" },
    { type: "sub",      criterionId: 33, label: "- Sea Export (Entry)" },
    { type: "sub",      criterionId: 34, label: "- Air Import (Entry)" },
    { type: "sub",      criterionId: 35, label: "- Air Export (Entry)" },
  ],
  CROSS_BORDER: [
    { type: "section",  label: "On-time Shipment" },
    { type: "category", criterionId: 36, label: "On-time Delivery",                           kpiDays: "3",          targetKpi: "98%" },
    { type: "sub",      criterionId: 37, label: "- Cross Border Import" },
    { type: "sub",      criterionId: 38, label: "- Cross Border Import - Actual" },
    { type: "sub",      criterionId: 39, label: "- Cross Border Export" },
    { type: "sub",      criterionId: 40, label: "- Cross Border Export - Actual" },
    { type: "category", criterionId: 41, label: "On time arrival at W/H vs slot time",        kpiDays: "0.5 Hrs.",   targetKpi: "98%" },
    { type: "sub",      criterionId: 42, label: "- Cross Border Import" },
    { type: "sub",      criterionId: 43, label: "- Cross Border Import - Actual" },
    { type: "sub",      criterionId: 44, label: "- Cross Border Export" },
    { type: "sub",      criterionId: 45, label: "- Cross Border Export - Actual" },
    { type: "category", criterionId: 46, label: "On-time Billing",                            kpiDays: "14",         targetKpi: "98%" },
    { type: "sub",      criterionId: 47, label: "- Cross Border Import" },
    { type: "sub",      criterionId: 48, label: "- Cross Border Export" },
    { type: "category", criterionId: 49, label: "Return entry under BIS19/Status 04 on time", kpiDays: "10",         targetKpi: "98%" },
    { type: "sub",      criterionId: 50, label: "- Cross Border Export (Entry)" },
    { type: "category", criterionId: 51, label: "Refund Import duty on time",                 kpiDays: "60",         targetKpi: "100%" },
    { type: "sub",      criterionId: 52, label: "- Cross Border Import (FORM D)" },
    { type: "sub",      criterionId: 53, label: "- Cross Border Import (FORM AI)" },
    { type: "category", criterionId: 54, label: "Communication and Solution response",        kpiDays: "",           targetKpi: "98%" },
    { type: "sub",      criterionId: 55, label: "- Contact person responds (Urgently case)",  kpiDays: "24 Hrs." },
    { type: "sub",      criterionId: 56, label: "- Contact person responds (Normally case)",  kpiDays: "48 Hrs." },
    { type: "section",  label: "Accuracy" },
    { type: "category", criterionId: 57, label: "Billing Accuracy",                           kpiDays: "Hit/Missed", targetKpi: "100%" },
    { type: "sub",      criterionId: 58, label: "- Cross Border Import" },
    { type: "sub",      criterionId: 59, label: "- Cross Border Export" },
    { type: "category", criterionId: 60, label: "Draft customs entry accuracy",               kpiDays: "Hit/Missed", targetKpi: "100%" },
    { type: "sub",      criterionId: 61, label: "- Cross Border Import" },
    { type: "sub",      criterionId: 62, label: "- Cross Border Export" },
    { type: "category", criterionId: 63, label: "Quality of Container",                       kpiDays: "Hit/Missed", targetKpi: "100%" },
    { type: "sub",      criterionId: 64, label: "- Import (Reject by SG)" },
    { type: "sub",      criterionId: 65, label: "- Import (Reject by KERRY)" },
    { type: "sub",      criterionId: 66, label: "- Export (Reject by GAC TH)" },
  ],
  OCEAN_FREIGHT: [
    { type: "section",  label: "Ocean Freight" },
    { type: "category", criterionId: 67, label: "Booking confirmation Lead-time",                           kpiDays: "within 48 hrs after Reckitt place booking requirement *container", targetKpi: "98%" },
    { type: "sub",      criterionId: 68, label: "- Booking confirmation Lead-time (actual)" },
    { type: "category", criterionId: 69, label: "Daily Communication",                                      kpiDays: "Booking Acknowledge within 24 hrs",                               targetKpi: "100%" },
    { type: "category", criterionId: 70, label: "On-time positioning of vessel departure",                  kpiDays: "Hit/Missed *container",                                           targetKpi: "98%" },
    { type: "sub",      criterionId: 71, label: "- On-time positioning of vessel departure (actual)" },
    { type: "category", criterionId: 72, label: "On-time positioning of Transit Time",                      kpiDays: "Hit/Missed *container",                                           targetKpi: "98%" },
    { type: "sub",      criterionId: 73, label: "- On-time positioning of Transit Time (actual)" },
    { type: "category", criterionId: 74, label: "Good equipment available",                                 kpiDays: "Hit/Missed *container",                                           targetKpi: "100%" },
    { type: "sub",      criterionId: 75, label: "- Good equipment available (actual)" },
    { type: "category", criterionId: 76, label: "Handling of documents accuracy",                           kpiDays: "Hit/Missed *set",                                                 targetKpi: "100%" },
    { type: "sub",      criterionId: 77, label: "- Handling of documents accuracy (actual)" },
    { type: "category", criterionId: 78, label: "Reactivity for urgencies",                                 kpiDays: "Hit/Missed",                                                     targetKpi: "100%" },
    { type: "category", criterionId: 79, label: "Information about problems",                               kpiDays: "Hit/Missed",                                                     targetKpi: "100%" },
    { type: "category", criterionId: 80, label: "On-time positioning of Freight invoice billing",           kpiDays: "within 7 days after vessel departure *set",                       targetKpi: "100%" },
    { type: "sub",      criterionId: 81, label: "- On-time positioning of Freight invoice billing (actual)" },
  ],
};
